### ISSUE TITLE
Please provide a way to disable some built-in languages

### ISSUE THREAD

**Issue by sirzooro** [fabioz/LiClipseText#10]
I have conflict between Cpp File editor provided by LiClipseText and Eclipse C++ editor. Some files are handled by one of them, some by another. I would like to always use Eclipse native editor, it provides additional features like code indexing which are missing in LiClipseText. I tried to somehow disable or remove cpp support using Window/Preferences dialog, but I was not able to find a way to do this. Please add such option there. If it is already possible to do this somehow, please add help text for this.

LiClipseText Feature	1.1.0.201610132326
Eclipse Neon.3 4.6.3

**Comment by fabioz** [comment]
It's not possible to completely remove it (when an editor is registered in Eclipse, it's always registered), but you can choose which is the default editor so that you always open it with CDT and not LiClipse -- just do: Ctrl+2, File Associations, click the extension you want and then set the default editor.

**Comment by fabioz** [comment]
Note that it's possible that Eclipse saved some configuration for a specific file. In that case, right-click the file and choose Open With > and choose the CDT editor.
