### ISSUE TITLE
Possible conflict with another plugin that extends Eclipse's Java/XML editors

### ISSUE THREAD

**Issue by harawata** [fabioz/LiClipseText#18]
Hello @fabioz ,

I'm an author of another Eclipse [plugin](https://marketplace.eclipse.org/content/mybatipse) which enhances the default Java and XML editors (e.g. auto-completion, hyperlink, validation).

Users reported that some of my plugin's features stoped working after they installed LiClipseText and I could verify the issue on my fresh installation of Eclipse 2019-12.
https://github.com/mybatis/mybatipse/issues/97
I am sorry to bother you, but from what I see, LiClipseText has its own editor and I am not sure how it affects my plugin.
It would be greatly appreciated if you could share some insights!

**Comment by fabioz** [comment]
Well, I'm not exactly sure how you add code-completion to existing editors. but maybe it's something related to the content type? LiClipseText adds content-types for the files it supports (you can see that in https://github.com/fabioz/LiClipseText/blob/master/plugins/org.brainwy.liclipsetext.editor/plugin.xml).

I think content-types are the only thing that goes globally into Eclipse... apart from that, LiClipse features should only be activated in the LiClipse-related editors (I do some hackery so that LiClipse is not the default -- i.e.: https://github.com/fabioz/LiClipseText/blob/master/plugins/org.brainwy.liclipsetext.editor/src/org/brainwy/liclipsetext/editor/LiClipseEditorOverride.java).

**Comment by harawata** [comment]
Thank you for the hint, @fabioz !
It might take some time, but I will look into it.

**Comment by harawata** [comment]
It was the content-type indeed.
I changed the priority of my plugin's content types and it resolved the issue, it seems.
Thanks again!
